version: "3.8"
services:

  jupyterhub:
    image: python-camp/jupyterhub
    build: .
    ports:
      - 8000:8000
    expose:
      - "8000"
    volumes:
      - /opt/jupyterhub/jupyterhub:/srv/jupyterhub
      - jupyterhub-data:/home
    command: ["bash", "-c", "./jh-startup.sh"]
    environment:
      - VIRTUAL_HOST=ec2-18-222-180-6.us-east-2.compute.amazonaws.com
      - VIRTUAL_PORT=8000

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  jupyterhub-data: