# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Python Camp: Programming for Beginners"
author: "GW Libraries & Academic Innovation"
logo: python-camp.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "parsons-yaml"]
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/gwu-libraries/python-camp  # Online location of your book
  path_to_book: textbook  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_substitutions:
    parsons_url: https://gwu-libraries.github.io/python-camp/parsons-problems/html
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
    - html_image

sphinx:
  recursive_update: true
  config:
    html_extra_path: ["parsons-assets", "static-assets"] # Parsons Problems .js, .css, and .html live here